export const EVENTS_FETCHED = "events.EVENTS_FETCHED";
export const USER_POSITION_SET = "events.USER_POSITION_SET";
export const USER_POSITION_FAILURE = "events.USER_POSITION_FAILURE";
export const EVENT_DISTANCE_CALCULATED = "events.EVENT_DISTANCE_CALCULATED";